


export type AutogenerationArgs = {
	date: Date
	name: string
}

export function autogenerationHeader(args: AutogenerationArgs) {
	return `/* eslint-disable */
/**
* ${args.name}
* Autogenerated on ${new Date().toJSON()} by typor8
* This is not intended to be manually modified. Git save the queen.
*/
`
}